### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"user@user.com",
    "password":"user123"
}

### register users
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "dewangga",
    "email": "test@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/v1/auth/verify/send
Content-Type: application/json

{
    "email": "adewanggan@gmail.com"
}

###
PUT http://localhost:3000/api/v1/auth/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyMzRhNmRmLTdiMGQtNDk3MS04ZjhhLWYwMGYyMjFmNzJmMSIsIm5hbWUiOiJkZXdhbmdnYSIsImVtYWlsIjoiaGFtYWRha2lub3NlQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGVGVzZKanB6MjZoY0xwSDJDZ2h0Ny5SNGo4c2ZiUEJrWjQxVVI4U2l4SWF2ZUV3QUNBV2llIiwiaXNfdmVyaWZpZWQiOmZhbHNlLCJyb2xlIjoiVVNFUiIsImNyZWF0ZWRBdCI6IjIwMjQtMDUtMjZUMDg6MzI6MTcuODc4WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDUtMjZUMDg6MzI6MTcuODc4WiIsInZlcmlmeSI6dHJ1ZSwiaWF0IjoxNzE2NzEyMzQ4LCJleHAiOjE3MTY3MTMyNDh9.NX8MbRCunhK8WyROeB9VwZGye4fejSz3vkMY5Qxf3IE

###
POST http://localhost:3000/api/v1/auth/forgotpassword
Content-Type: application/json

{
    "email": "hamadakinose@gmail.com"
}

###
POST http://localhost:3000/api/v1/auth/resetpassword/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4NmMyZWQxLTc5MzYtNDg5Yy1hOTI5LTQ1ZDQ2ZGEwZmIwNSIsInBhc3N3b3JkIjoiJDJiJDEwJG82WjNBbmRRZDYzbTdCNHZ2RWpWRmV6WU1qNjhKazZ2eVhkc1FFV2Q5Y05PR0xRRUhvNExhIiwiaWF0IjoxNzE2Mzg0ODEwLCJleHAiOjE3MTYzODU3MTB9.9-oL_3PxZIRQKNrr5Rwz7fO9rX9j0TWQ3iM-zQlBCgg
Content-Type: application/json

{
    "password": "123",
    "confirm": "123"
}

### GET PROFILES
GET http://localhost:3000/api/v1/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4OGE0YTZkLTk0OGItNDAwNC1iODZjLWM5MzVjNDMyYmYwZCIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJVU0VSIiwiY3JlYXRlZEF0IjoiMjAyNC0wNi0wNVQxMjo0Mzo0Mi4yMzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0wNVQxMjo0Mzo0Mi4yMzlaIiwiaWF0IjoxNzE4MTk2Njg4fQ.y1MXz9-T64VXEzcANJ2R-sed1OyU7KFk0j7PlOaV_Xc

### GET ALL USER (BY ADMIN)
GET http://localhost:3000/api/v1/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5ZDBkMTc4LTNiZTgtNGQ4OS04NGFkLTJlYmRhZWI2YTY1YyIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMjQtMDUtMjRUMDc6MjY6NDQuMDcwWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDUtMjRUMDc6MjY6NDQuMDcwWiIsImlhdCI6MTcxNjUzNjM5OX0.0G9mTy9AFLy09Dabz_ohr7cx3KAQkllINuRnLqzwNMA

### UPDATE PROFILES BY USER_ID
PUT http://localhost:3000/api/v1/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4OGE0YTZkLTk0OGItNDAwNC1iODZjLWM5MzVjNDMyYmYwZCIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJVU0VSIiwiY3JlYXRlZEF0IjoiMjAyNC0wNi0wNVQxMjo0Mzo0Mi4yMzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0wNVQxMjo0Mzo0Mi4yMzlaIiwiaWF0IjoxNzE4MTk2Njg4fQ.y1MXz9-T64VXEzcANJ2R-sed1OyU7KFk0j7PlOaV_Xc
Content-Type: application/json

{
  "name": "User",
  "address": "Jalan user",
  "phone": "123456789",
  "occupation": "USER",
  "birthdate": "2010-10-10"
}

###
GET http://localhost:3000/api/v1/notification/a234a6df-7b0d-4971-8f8a-f00f221f72f1

###
GET http://localhost:3000/api/v1/notification/a234a6df-7b0d-4971-8f8a-f00f221f72f1/read

###
GET http://localhost:3000/api/v1/tax

###
GET http://localhost:3000/api/v1/category/

###
GET http://localhost:3000/api/v1/category/4b4e269-1b22-4a07-977a-beb4870d4d00

###
PUT http://localhost:3000/api/v1/auth/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyMzRhNmRmLTdiMGQtNDk3MS04ZjhhLWYwMGYyMjFmNzJmMSIsIm5hbWUiOiJkZXdhbmdnYSIsImVtYWlsIjoiaGFtYWRha2lub3NlQGdtYWlsLmNvbSIsImlzX3ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoiVVNFUiIsImNyZWF0ZWRBdCI6IjIwMjQtMDUtMjZUMDg6MzI6MTcuODc4WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDUtMjZUMDg6MzI6MzkuMzE2WiIsImlhdCI6MTcxNjgyOTIxN30.-85gUS65gbfJyJP9-2aw0dWU6VZhVd9Zy6fGpaeToCQ
Content-Type: application/json

{
    "password": "123",
    "confirm": "123"
}

###
POST http://localhost:3000/api/v1/auth/googlelogin
Content-Type: application/json

{
    "access_token": "ya29.a0AXooCgvepkly4ifXAsIsbPoNhg_BfLmAukcCoaEPH2XTs2gFNm-mnIRnoaEyAe3kd1Xbsm_GkRAFay_3ohXpPrGVqupoT_u_s-LP6vrsFvgDS__4nw0Za3y0te45qFT9-aacIpKBU9YVQGsa-09MyX-Qaj84NdsKvpFtaCgYKAd0SARISFQHGX2MiRKMHKtHQ3GbyVrlzmJ8MyQ0171"
}

### Create a Booking
POST http://localhost:3000/api/v1/bookings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4OGE0YTZkLTk0OGItNDAwNC1iODZjLWM5MzVjNDMyYmYwZCIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJVU0VSIiwiY3JlYXRlZEF0IjoiMjAyNC0wNi0wNVQxMjo0Mzo0Mi4yMzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xMlQxMzowMzozMC45NDBaIiwiaWF0IjoxNzE4NjExOTE2fQ.NkOHgqkMqls54aJd4HRR0Al4TG6ZN6fdcQIkK9uxAcw
Content-Type: application/json

{
  "flight_class_id": "26b1deef-1868-4de2-ba24-bce2d1abe136",
  "include_return": false,
  "passengers": [
    {
      "name": "adi irawan",
      "birthdate": "2003-09-13",
      "identity_id": "KTP",
      "citizenship": "Indonesia",
      "category": "adult"
    }
  ]
}

### Get all Booking
GET http://localhost:3000/api/v1/bookings?page=1&startDate=2024-06-10&endDate=2024-06-10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4OGE0YTZkLTk0OGItNDAwNC1iODZjLWM5MzVjNDMyYmYwZCIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJVU0VSIiwiY3JlYXRlZEF0IjoiMjAyNC0wNi0wNVQxMjo0Mzo0Mi4yMzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xMlQxMzowMzozMC45NDBaIiwiaWF0IjoxNzE4NjE1MjA3fQ.14Av1QqZW2mbP5JHJJpheMOUePQIvWgtoX7_W1f0Sk0

### Get Booking by id
GET http://localhost:3000/api/v1/bookings/9b12beeb-3e11-4197-8bc4-48608765742e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NWNiMjcwLThjMjktNGU5Mi1hZmE4LTFhNGY5ODY0ZTdlOSIsIm5hbWUiOiJEZXdhbmdnYSBOYW5kYSBBcmp1bmEiLCJlbWFpbCI6ImFkZXdhbmdnYW5AZ21haWwuY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJVU0VSIiwiY3JlYXRlZEF0IjoiMjAyNC0wNS0yOVQxNTozOToxMy45MDdaIiwidXBkYXRlZEF0IjoiMjAyNC0wNS0zMFQxNDo1ODowMS41MDFaIiwiaWF0IjoxNzE3MDgxMDgxfQ.b52Acyzh-gjZAiEuU5XI-tlDjaWrTRFh8msC6mq1Gvk

### Get Flights Request
GET http://localhost:3000/api/v1/flight?from=HLP&p=1&sc=FIRST_CLASS&page=1

### Get Most Favorited Flights
GET http://localhost:3000/api/v1/flight/favorite

### Get Flight by id
GET http://localhost:3000/api/v1/flight/d33eb61c-47a0-4153-b526-bd4d8d49f46b

### Get All Plane
GET http://localhost:3000/api/v1/plane

### Get Plane by ID or Plane Code
GET http://localhost:3000/api/v1/plane/GD-105

### Get All Airport
GET http://localhost:3000/api/v1/airport

### Get Airport by ID or Airport Code
GET http://localhost:3000/api/v1/airport/CGK

### Update Payment
PUT http://localhost:3000/api/v1/payments/5396e202-4665-4f2b-9846-452087b77b1d
