const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
async function PlaneSeeder() {
  return new Promise(async (resolve, reject) => {
    let data = [
      {
        plane_code: "GD-105",
        airline: "Garuda Indonesia",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "LA-202",
        airline: "Lion Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SJ-303",
        airline: "Sriwijaya Air",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "IA-404",
        airline: "Indonesia AirAsia",
        economy_seat: 70,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-505",
        airline: "Batik Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CT-606",
        airline: "Citilink",
        economy_seat: 50,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "TS-707",
        airline: "TransNusa",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SP-808",
        airline: "Susi Air",
        economy_seat: 40,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "MG-909",
        airline: "NAM Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KV-1010",
        airline: "Wings Air",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "AA-1111",
        airline: "American Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-1212",
        airline: "British Airways",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "EM-1313",
        airline: "Emirates",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SQ-1414",
        airline: "Singapore Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "QF-1515",
        airline: "Qantas",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "LH-1616",
        airline: "Lufthansa",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "AF-1717",
        airline: "Air France",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KE-1818",
        airline: "Korean Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "JL-1919",
        airline: "Japan Airlines",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CX-2020",
        airline: "Cathay Pacific",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "GD-10",
        airline: "Garuda Indonesia",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "LA-20",
        airline: "Lion Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SJ-30",
        airline: "Sriwijaya Air",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "IA-44",
        airline: "Indonesia AirAsia",
        economy_seat: 70,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-51",
        airline: "Batik Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CT-66",
        airline: "Citilink",
        economy_seat: 50,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "TS-70",
        airline: "TransNusa",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SP-80",
        airline: "Susi Air",
        economy_seat: 40,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "MG-99",
        airline: "NAM Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KV-101",
        airline: "Wings Air",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "AA-111",
        airline: "American Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-122",
        airline: "British Airways",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "EM-13",
        airline: "Emirates",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SQ-144",
        airline: "Singapore Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "QF-15",
        airline: "Qantas",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "LH-116",
        airline: "Lufthansa",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "AF-177",
        airline: "Air France",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KE-118",
        airline: "Korean Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "JL-199",
        airline: "Japan Airlines",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CX-200",
        airline: "Cathay Pacific",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "GD-1056",
        airline: "Garuda Indonesia",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "LA-2026",
        airline: "Lion Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SJ-3036",
        airline: "Sriwijaya Air",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "IA-4046",
        airline: "Indonesia AirAsia",
        economy_seat: 70,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-5056",
        airline: "Batik Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CT-12",
        airline: "Citilink",
        economy_seat: 50,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "TS-12",
        airline: "TransNusa",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SP-12",
        airline: "Susi Air",
        economy_seat: 40,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "MG-12",
        airline: "NAM Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KV-13",
        airline: "Wings Air",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "AA-12",
        airline: "American Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-13",
        airline: "British Airways",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "EM-14",
        airline: "Emirates",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SQ-14",
        airline: "Singapore Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "QF-14",
        airline: "Qantas",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "LH-12",
        airline: "Lufthansa",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "AF-12",
        airline: "Air France",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KE-14",
        airline: "Korean Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "JL-12",
        airline: "Japan Airlines",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CX-14",
        airline: "Cathay Pacific",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "GD-123",
        airline: "Garuda Indonesia",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "LA-143",
        airline: "Lion Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SJ-143",
        airline: "Sriwijaya Air",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "IA-143",
        airline: "Indonesia AirAsia",
        economy_seat: 70,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-143",
        airline: "Batik Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CT-6123",
        airline: "Citilink",
        economy_seat: 50,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "TS-143",
        airline: "TransNusa",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SP-143",
        airline: "Susi Air",
        economy_seat: 40,
        premium_economy_seat: 10,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "MG-123",
        airline: "NAM Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KV-123",
        airline: "Wings Air",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "AA-123",
        airline: "American Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "BA-123",
        airline: "British Airways",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "EM-143",
        airline: "Emirates",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "SQ-143",
        airline: "Singapore Airlines",
        economy_seat: 50,
        premium_economy_seat: 15,
        business_seat: 5,
        first_class_seat: 7,
      },
      {
        plane_code: "QF-123",
        airline: "Qantas",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "LH-123",
        airline: "Lufthansa",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "AF-143",
        airline: "Air France",
        economy_seat: 55,
        premium_economy_seat: 15,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "KE-143",
        airline: "Korean Air",
        economy_seat: 60,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "JL-123",
        airline: "Japan Airlines",
        economy_seat: 50,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
      {
        plane_code: "CX-123",
        airline: "Cathay Pacific",
        economy_seat: 55,
        premium_economy_seat: 20,
        business_seat: 10,
        first_class_seat: 7,
      },
    ];

    try {
      const deletePLane = await prisma.plane.deleteMany({});
      const planeCreate = await prisma.plane.createMany({
        data: data,
      });
      resolve("Success create plane seeds");
    } catch (error) {
      reject(error.message);
    }
  });
}

module.exports = PlaneSeeder;
